name: "Github Action Merge Dependabot"
description: "Automatically merge dependabot PRs"
inputs:
  github-token:
    description: "A GitHub token."
    required: true
  exclude:
    description: "Packages that you want to manually review before upgrading"
    required: false
    default: []
runs:
  using: "node12"
  main: "index.js"
