name: CI
on: pull_request
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          approve-only: true
